// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using appdotnet;

#nullable disable

namespace app_dotnet.Migrations
{
    [DbContext(typeof(TareasContext))]
    partial class TareasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("appdotnet.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Peso")
                        .HasColumnType("integer");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("b0e000d3-f29c-4fed-8747-3bd0734f871e"),
                            Nombre = "Pending",
                            Peso = 20
                        },
                        new
                        {
                            CategoriaId = new Guid("b0e000d3-f29c-4fed-8747-3bd0734f8711"),
                            Nombre = "Personal",
                            Peso = 50
                        });
                });

            modelBuilder.Entity("appdotnet.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("b0e000d3-f29c-4fed-8747-3bd0734f8730"),
                            CategoriaId = new Guid("b0e000d3-f29c-4fed-8747-3bd0734f871e"),
                            FechaCreacion = new DateTime(2024, 8, 1, 5, 4, 47, 522, DateTimeKind.Utc).AddTicks(2665),
                            PrioridadTarea = 1,
                            Titulo = "Review public services pays"
                        },
                        new
                        {
                            TareaId = new Guid("b0e000d3-f29c-4fed-8747-3bd0734f8721"),
                            CategoriaId = new Guid("b0e000d3-f29c-4fed-8747-3bd0734f8711"),
                            FechaCreacion = new DateTime(2024, 8, 1, 5, 4, 47, 522, DateTimeKind.Utc).AddTicks(2670),
                            PrioridadTarea = 0,
                            Titulo = "Netflix movie end"
                        });
                });

            modelBuilder.Entity("appdotnet.Models.Tarea", b =>
                {
                    b.HasOne("appdotnet.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("appdotnet.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
